version: '3.7'

services:
  db:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/etc/postgresql/data
    restart: always
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data
  web:
    image: amazon-crawler:python2
    build: ./crawler
    volumes:
      - .:/public-amazon-crawler/data
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
